alg_name: 'bo'

model:
    _target_: algorithms.BO
    n_init: 10
    init_sampler_type: 'permutation'
    acqf_init_sampler_type: 'permutation'
    acqf_type: 'EI'
    acqf_opt_type: 'random'
    kernel_type: 'vs'

